// user profile
export const SET_USER_PROFILE = 'SET_USER_PROFILE'
export const GET_USER_PROFILE = 'GET_USER_PROFILE'
export const GET_POSTER_OF_THE_DAY = 'GET_POSTER_OF_THE_DAY'
export const SET_POSTER_OF_THE_DAY = 'SET_POSTER_OF_THE_DAY'
export const SEARCH_POSTER_OF_THE_DAY = 'SEARCH_POSTER_OF_THE_DAY'
